import 'package:flutter/material.dart';
import 'package:listapp/model/list.dart';

//Create Stateless widget
class HomePage extends StatelessWidget {
  const HomePage({super.key});

  @override
  Widget build(BuildContext context) {
    //Initilize InfoList
    final infoList = InfoList();
    return Scaffold(
      appBar: AppBar(
        title: const Text('Info List'),
        centerTitle: true,
        backgroundColor: Colors.blueGrey,
      ),
      //Use ValueListenableBuilder()
      body: ValueListenableBuilder(
        //supply it with InfoList() directly
        valueListenable: InfoList(),
        builder: (context, value, child) {
          //Initialize an infos that will have the value
          final infos = value;
          //This will return a ListView.builder()
          return ListView.builder(
            itemCount: infoList.length,
            itemBuilder: (context, index) {
              //Initialize a info that will have infos[index]
              final info = infos[index];
              return Dismissible(
                //onDismissed hold a functionality where we can
                //remove a data on the list swipping on thel left or right
                //direction
                onDismissed: (direction) {
                  InfoList().remove(info: info);
                },
                //Id generated by the uuid
                key: ValueKey(info.id),
                //We can display the list
                child: ListTile(
                  leading: const Icon(
                    Icons.account_circle_rounded,
                    color: Colors.blueGrey,
                    size: 50,
                  ),
                  title: Text('${info.firstname} ${info.lastname}'),
                  subtitle: Text(info.address),
                ),
              );
            },
          );
        },
      ),
      floatingActionButton: FloatingActionButton(
        //Navigate to AddListPage class
        onPressed: () async {
          await Navigator.of(context).pushNamed('/addlist');
        },
        backgroundColor: Colors.blueGrey,
        child: const Icon(
          Icons.person_add_rounded,
          color: Colors.white,
        ),
      ),
    );
  }
}
